# Generated by Django 2.2.1 on 2020-02-19 01:08

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(null=True, validators=[inventario.validators.ValidateMayorCero]),
        ),
    ]
