# Generated by Django 2.2.1 on 2019-11-15 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='',
        ),
    ]
