# Generated by Django 2.2.1 on 2019-11-22 04:25

import adquisiciones.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adquisiciones', '0002_remove_proveedor_'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenadq',
            name='factura',
            field=models.IntegerField(default=0, validators=[adquisiciones.validators.ValidateMayorCero]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenadq',
            name='fecha_factura',
            field=models.DateField(null=True),
            preserve_default=False,
        ),
    ]
