# Generated by Django 2.2.1 on 2019-11-20 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_producto_ubicacion'),
        ('salidas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pre_prod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='salida',
            name='tipo',
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('total', models.IntegerField()),
                ('devolucion', models.DateField()),
                ('id_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Funcionario')),
                ('id_recinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Recinto')),
                ('productos', models.ManyToManyField(through='salidas.Pre_prod', to='inventario.Producto')),
            ],
        ),
        migrations.AddField(
            model_name='pre_prod',
            name='id_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salidas.Prestamo'),
        ),
        migrations.AddField(
            model_name='pre_prod',
            name='id_prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto'),
        ),
    ]
