# Generated by Django 2.2.1 on 2020-03-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_auto_20200301_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='pre_prod',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sal_prod',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
