# Generated by Django 2.2.1 on 2019-11-21 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salidas', '0002_auto_20191120_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id_recinto',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_recinto',
            field=models.ManyToManyField(to='salidas.Recinto'),
        ),
    ]
