# Generated by Django 2.2.1 on 2019-11-11 22:00
import inventario.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('estado', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_prod', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cod_barra', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.CharField(max_length=100)),
                ('precio_compra', models.IntegerField(validators=[inventario.validators.ValidateMayorCero])),
                ('stock', models.IntegerField(default=0, validators=[inventario.validators.ValidateNumeroPositivo])),
                ('stock_min', models.IntegerField(default=0, validators=[inventario.validators.ValidateNumeroPositivo])),
                ('merma', models.IntegerField(default=0, validators=[inventario.validators.ValidateNumeroPositivo])),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('inventariado', 'Inventariado')], default='pendiente', max_length=20)),
                ('estado_prod', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id_cat', models.ManyToManyField(to='inventario.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTemporalProducto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_compra', models.IntegerField(validators=[inventario.validators.ValidateMayorCero])),
                ('stock', models.IntegerField(blank=True, null=True, validators=[inventario.validators.ValidateMayorCero])),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('id_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.Producto')),
            ],
        ),
    ]
