# Generated by Django 2.2.1 on 2020-03-01 21:45

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(blank=True, null=True, validators=[inventario.validators.ValidateMayorCero]),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_min',
            field=models.IntegerField(default=0, null=True, validators=[inventario.validators.ValidateNumeroPositivo]),
        ),
    ]
