# Generated by Django 2.2.1 on 2019-11-07 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_venta',
        ),
        migrations.RemoveField(
            model_name='registrotemporalproducto',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='registrotemporalproducto',
            name='precio_ponderado',
        ),
        migrations.RemoveField(
            model_name='registrotemporalproducto',
            name='precio_venta',
        ),
    ]
