# Generated by Django 2.2.1 on 2019-11-14 21:53

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ubicacion',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrotemporalproducto',
            name='precio_compra',
            field=models.IntegerField(blank=True, null=True, validators=[inventario.validators.ValidateMayorCero]),
        ),
    ]
