# Generated by Django 2.2.1 on 2020-03-01 21:53

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200301_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(default=0, validators=[inventario.validators.ValidateMayorCero]),
            preserve_default=False,
        ),
    ]
