# Generated by Django 2.2.1 on 2020-02-20 22:13

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20200218_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_cat',
            field=models.ManyToManyField(null=True, to='inventario.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_min',
            field=models.IntegerField(default=0, null=True, validators=[inventario.validators.ValidateNumeroPositivo]),
        ),
    ]
