# Generated by Django 2.2.1 on 2019-11-14 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20191114_1853'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ubicacion',
        ),
    ]
