# Generated by Django 2.2.1 on 2020-03-01 16:47

from django.db import migrations, models
import inventario.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20200220_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id_cat',
            field=models.ManyToManyField(to='inventario.Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_compra',
            field=models.IntegerField(default=0, validators=[inventario.validators.ValidateMayorCero]),
            preserve_default=False,
        ),
    ]
