# Generated by Django 2.2.1 on 2020-03-01 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20200301_1859'),
        ('inventario', '0002_auto_20200218_2208'),
    ]

    operations = [
    ]
