# Generated by Django 2.2.1 on 2020-03-10 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20200304_2103'),
        ('inventario', '0006_auto_20200303_2202'),
    ]

    operations = [
    ]
