# Generated by Django 2.2.1 on 2019-11-08 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='codigo',
            field=models.CharField(default=0, max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
