# Generated by Django 2.2.1 on 2019-11-06 23:22

from django.db import migrations, models
import proveedor.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=13, unique=True, validators=[proveedor.validators.ValidateRut])),
                ('nombre', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('email', models.CharField(default='N/A', max_length=30, unique=True)),
                ('estado', models.BooleanField(default=True)),
                ('nom_cont', models.CharField(max_length=20)),
                ('giro', models.CharField(max_length=100)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
